package com.cardcombat;
import java.util.*;import org.bukkit.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.inventory.*;import org.bukkit.plugin.java.JavaPlugin;import org.bukkit.scheduler.BukkitRunnable;
public final class CardCombatPlugin extends JavaPlugin implements Listener{
 private CardManager cards;private ProfileManager profiles;private EconomyManager economy;private ChallengeManager challenges;private MatchmakingManager matchmaking;private PracticeBotManager bots;private RitualManager rituals;private final Set<UUID>battle=new HashSet<UUID>();private final Map<UUID,ItemStack[]>saved=new HashMap<UUID,ItemStack[]>();private final Map<UUID,ItemStack>off=new HashMap<UUID,ItemStack>();private final Set<UUID>mageArmor=new HashSet<UUID>();private final Set<UUID>armorParticlesOff=new HashSet<UUID>();
 public void onEnable(){saveDefaultConfig();ensureCards();cards=new CardManager(this);cards.load();profiles=new ProfileManager(this);profiles.load();economy=new EconomyManager(this);challenges=new ChallengeManager(this);matchmaking=new MatchmakingManager(this);bots=new PracticeBotManager(this,cards);rituals=new RitualManager(this);getServer().getPluginManager().registerEvents(this,this);getServer().getPluginManager().registerEvents(new CombatListener(this),this);register();new BukkitRunnable(){public void run(){cards.run();bots.tick();hud();for(Player p:Bukkit.getOnlinePlayers())if(isBattleMode(p))profiles.cosmeticTick(p);}}.runTaskTimer(this,20L,20L);new BukkitRunnable(){public void run(){for(Player p:Bukkit.getOnlinePlayers())if(isBattleMode(p)&&p.isOnline())cards.mageArmorParticles(p);}}.runTaskTimer(this,3L,3L);getLogger().info("BattleCards 4.0.0 enabled.");}
 private void register(){CardCommand bc=new CardCommand(this);getCommand("battlecards").setExecutor(bc);getCommand("battlecards").setTabCompleter(bc);getCommand("challenge").setExecutor(new ChallengeCommand(this,challenges));getCommand("accept").setExecutor(new AcceptCommand(this,challenges));getCommand("shop").setExecutor(new ShopCommand(this));getCommand("missions").setExecutor(new MissionsCommand(this));getCommand("match").setExecutor(new MatchCommand(this));getCommand("bot").setExecutor(new PracticeBotCommand(this));getCommand("ritual").setExecutor(new RitualCommand(this));}
 private void ensureCards(){if(!new java.io.File(getDataFolder(),"cards.yml").exists())saveResource("cards.yml",false);}
 public void onDisable(){if(bots!=null)bots.shutdown();if(matchmaking!=null)matchmaking.shutdown();if(challenges!=null)challenges.shutdown();for(Player p:Bukkit.getOnlinePlayers())if(isBattleMode(p))exitBattleMode(p);}
 public CardManager cards(){return cards;}public ProfileManager profiles(){return profiles;}public EconomyManager economy(){return economy;}public ChallengeManager challenges(){return challenges;}public MatchmakingManager matchmaking(){return matchmaking;}public PracticeBotManager practiceBots(){return bots;}public RitualManager rituals(){return rituals;}
 public String[] classes(){return new String[]{"Shadow","Fire","Water","Earth","Wind","Light","Dragon","Ice","Fighting","Mech","Magnitized","Soul"};}
 public boolean isAdmin(Player p){return p.isOp()||p.hasPermission("battlecards.admin");}public boolean isStaff(Player p){return isAdmin(p)||p.hasPermission("battlecards.staff")&&getConfig().getBoolean("settings.staff.bypass-permission",true);}public boolean isBattleMode(Player p){return battle.contains(p.getUniqueId());}public boolean isMageArmorMode(Player p){return mageArmor.contains(p.getUniqueId());}public boolean isArmorParticlesEnabled(Player p){return !armorParticlesOff.contains(p.getUniqueId());}public void toggleMageArmorMode(Player p){if(!isBattleMode(p)){p.sendMessage(ChatColor.RED+"You must enter BattleCards mode first.");return;}if(!mageArmor.remove(p.getUniqueId())){mageArmor.add(p.getUniqueId());p.sendMessage(ChatColor.LIGHT_PURPLE+"Mage Armor enabled.");}else p.sendMessage(ChatColor.YELLOW+"Mage Armor disabled.");}public void toggleArmorParticles(Player p){if(!armorParticlesOff.remove(p.getUniqueId())){armorParticlesOff.add(p.getUniqueId());p.sendMessage(ChatColor.YELLOW+"Armor particles disabled.");}else p.sendMessage(ChatColor.GREEN+"Armor particles enabled.");}
 public void enterBattleMode(Player p){if(!p.hasPermission("battlecards.play")&&!isStaff(p)){p.sendMessage(ChatColor.RED+"You don't have permission.");return;}if(isBattleMode(p))return;battle.add(p.getUniqueId());saved.put(p.getUniqueId(),p.getInventory().getContents().clone());off.put(p.getUniqueId(),p.getInventory().getItemInOffHand());p.getInventory().clear();cards.resetMana(p);cards.refreshHotbar(p);p.sendMessage(ChatColor.GREEN+"BattleCards mode activated.");}
 public void exitBattleMode(Player p){if(!isBattleMode(p))return;battle.remove(p.getUniqueId());mageArmor.remove(p.getUniqueId());armorParticlesOff.remove(p.getUniqueId());cards.stopPlayanoo(p);ItemStack[]x=saved.remove(p.getUniqueId());ItemStack o=off.remove(p.getUniqueId());p.getInventory().clear();if(x!=null){p.getInventory().setContents(x);p.getInventory().setItemInOffHand(o);}cards.removePlayer(p);p.sendMessage(ChatColor.RED+"BattleCards mode disabled.");}
 private void hud(){for(Player p:Bukkit.getOnlinePlayers())if(isBattleMode(p)){String s=ChatColor.AQUA+"Mana: "+cards.getMana(p)+"/"+getConfig().getInt("settings.mana.max",100);if(cards.isCombatTagged(p))s+=ChatColor.RED+" | COMBAT "+(cards.combatRemaining(p)+999)/1000+"s";p.spigot().sendMessage(net.md_5.bungee.api.ChatMessageType.ACTION_BAR,new net.md_5.bungee.api.chat.TextComponent(s));}}
 public String msg(String k){return color(getConfig().getString("messages."+k,""));}public String color(String s){return ChatColor.translateAlternateColorCodes('&',s==null?"":s);}
}
