package com.cardcombat;
import java.util.*;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.event.inventory.InventoryType;
public final class CardCommand implements CommandExecutor,TabCompleter{
 private final CardCombatPlugin p;public CardCommand(CardCombatPlugin p){this.p=p;}
 public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player)){s.sendMessage("Players only.");return true;}Player x=(Player)s;if(a.length==0||a[0].equalsIgnoreCase("help")){help(x);return true;}String sub=a[0].toLowerCase();if(sub.equals("player")){p.enterBattleMode(x);return true;}if(sub.equals("stop")){p.exitBattleMode(x);return true;}if(sub.equals("profile")||sub.equals("cosmetics")||sub.equals("titles")){x.openInventory(new CardMenu(p).createProfile(x));return true;}if(sub.equals("cards")||sub.equals("library")){if(!p.isBattleMode(x)){x.sendMessage(p.msg("not-mode"));return true;}x.openInventory(new CardMenu(p).createLibrary(x));return true;}if(sub.equals("class")){chooseClass(x,a);return true;}if(sub.equals("reset")){if(!p.isStaff(x)&&!x.hasPermission("battlecards.class.reset")){x.sendMessage(ChatColor.RED+"No permission.");return true;}p.profiles().resetClass(x);x.sendMessage(ChatColor.GREEN+"Class reset.");return true;}if(sub.equals("magearmor")){p.toggleMageArmorMode(x);return true;}if(sub.equals("armor")){if(a.length>1&&a[1].equalsIgnoreCase("particles"))p.toggleArmorParticles(x);else p.toggleMageArmorMode(x);return true;}if(sub.equals("reload")){if(!p.isStaff(x)){x.sendMessage(ChatColor.RED+"Staff only.");return true;}p.cards().load();x.sendMessage(ChatColor.GREEN+"Reloaded cards.yml.");return true;}if(sub.equals("give")){if(!p.isStaff(x)||a.length<3)return true;Player t=Bukkit.getPlayerExact(a[1]);if(t==null)return true;ItemStack i=p.cards().createItem(a[2],1);if(i!=null)t.getInventory().addItem(i);return true;}if(sub.equals("create")){if(!p.isStaff(x)||a.length<4)return true;try{double power=Double.parseDouble(a[3]);x.sendMessage(p.cards().createBasicCard(a[1],a[2],"DAMAGE",power)?ChatColor.GREEN+"Created.":ChatColor.RED+"Could not create.");}catch(Exception e){x.sendMessage(ChatColor.RED+"Power must be a number.");}return true;}if(sub.equals("delete")){if(!p.isStaff(x)||a.length<2)return true;x.sendMessage(p.cards().deleteCard(a[1])?ChatColor.GREEN+"Deleted.":ChatColor.RED+"Not found.");return true;}return true;}
 private void chooseClass(Player p,String[]a){if(a.length<2){p.sendMessage(ChatColor.YELLOW+"Classes: "+String.join(", ",this.p.classes()));return;}if(p.profiles().hasClass(p)){p.sendMessage(ChatColor.RED+"You already chose "+p.profiles().getClass(p)+".");return;}for(String c:this.p.classes())if(c.equalsIgnoreCase(a[1])){p.profiles().setClass(p,c);p.sendMessage(ChatColor.GREEN+"Class chosen: "+c);this.p.cards().refreshHotbar(p);return;}p.sendMessage(ChatColor.RED+"Unknown class.");}
 private void cards(Player p,String cat){String cls=this.p.profiles().getClass(p);if(cls.isEmpty()){p.sendMessage(ChatColor.RED+"Choose a class first.");return;}p.sendMessage(ChatColor.GOLD+"=== "+cls+" Cards ===");int n=0;for(CardDefinition c:this.p.cards().all()){if(!c.cardClass.equalsIgnoreCase(cls))continue;if(c.type.startsWith("DOMAIN_")||c.type.startsWith("PLAYANOO")||c.type.equals("FORM"))continue;boolean own=this.p.isStaff(p)||this.p.economy().owns(p,c.id);p.sendMessage((own?ChatColor.GREEN+"[UNLOCKED] ":ChatColor.RED+"[LOCKED] ")+ChatColor.WHITE+c.id+ChatColor.GRAY+" — "+ChatColor.stripColor(ChatColor.translateAlternateColorCodes('&',c.name)));if(++n>=54)break;}p.sendMessage(ChatColor.GRAY+"Use /shop to unlock locked cards.");}
 private void profile(Player p){p.sendMessage(ChatColor.GOLD+"=== Battle Profile ===");p.sendMessage(ChatColor.YELLOW+"Class: "+p.profiles().getClass(p));p.sendMessage(ChatColor.YELLOW+"Wins: "+p.profiles().getWins(p)+"  Losses: "+p.profiles().getLosses(p)+"  Shards: "+p.profiles().getShards(p));p.sendMessage(ChatColor.YELLOW+"CC: "+p.economy().getCoins(p));}
 private void help(Player p){p.sendMessage(ChatColor.GOLD+"/bc player | stop | cards | class <class> | profile | reset");p.sendMessage(ChatColor.GOLD+"/shop | /missions | /match queue|leave|status | /bot easy|normal|hard [class]");}
 public List<String>onTabComplete(CommandSender s,Command c,String a,String[]x){if(x.length==1)return Arrays.asList("player","stop","cards","class","profile","reset","armor","reload","help");if(x.length==2&&x[0].equalsIgnoreCase("class"))return Arrays.asList(this.p.classes());return Collections.emptyList();}
}
