package com.cardcombat;
import java.util.*;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.scheduler.BukkitRunnable;
public final class ChallengeManager{private final CardCombatPlugin p;private final Map<UUID,UUID>pending=new HashMap<UUID,UUID>();private final Map<UUID,Match>matches=new HashMap<UUID,Match>();private final Map<UUID,Location>returns=new HashMap<UUID,Location>();public ChallengeManager(CardCombatPlugin p){this.p=p;}
 public void challenge(Player a,Player b){if(a.equals(b)||!p.isBattleMode(a)||!p.isBattleMode(b)){a.sendMessage(ChatColor.RED+"Both players must be in BattleCards mode.");return;}if(isInMatch(a.getUniqueId())||isInMatch(b.getUniqueId())){a.sendMessage(ChatColor.RED+"One of you is already in a match.");return;}pending.put(b.getUniqueId(),a.getUniqueId());a.sendMessage(ChatColor.GREEN+"Challenge sent to "+b.getName()+".");b.sendMessage(ChatColor.YELLOW+a.getName()+" challenged you. Use /accept.");new BukkitRunnable(){public void run(){UUID x=pending.get(b.getUniqueId());if(a.getUniqueId().equals(x)){pending.remove(b.getUniqueId());b.sendMessage(ChatColor.RED+"Challenge expired.");}}}.runTaskLater(p,20L*p.getConfig().getInt("settings.battle.challenge-timeout-seconds",30));}
 public void accept(Player b){UUID u=pending.remove(b.getUniqueId());if(u==null){b.sendMessage(ChatColor.RED+"You have no pending challenge.");return;}Player a=Bukkit.getPlayer(u);if(a==null){b.sendMessage(ChatColor.RED+"That player is offline.");return;}start(a,b,false);}
 public void startOfficial(Player a,Player b){start(a,b,true);}private void start(final Player a,final Player b,final boolean official){if(a==null||b==null)return;if(isInMatch(a.getUniqueId())||isInMatch(b.getUniqueId()))return;Location la=a.getLocation().clone(),lb=b.getLocation().clone();returns.put(a.getUniqueId(),la);returns.put(b.getUniqueId(),lb);Match m=new Match(a.getUniqueId(),b.getUniqueId(),official);matches.put(a.getUniqueId(),m);matches.put(b.getUniqueId(),m);Location s1=readLocation("spawn1"),s2=readLocation("spawn2");if(s1!=null)a.teleport(s1);if(s2!=null)b.teleport(s2);countdown(a,b,m);}
 private void countdown(final Player a,final Player b,final Match m){new BukkitRunnable(){int n=3;public void run(){if(!isInMatch(a.getUniqueId())||!isInMatch(b.getUniqueId())){cancel();return;}if(n<=0){a.sendMessage(ChatColor.GREEN+"FIGHT!");b.sendMessage(ChatColor.GREEN+"FIGHT!");cancel();return;}a.sendMessage(ChatColor.YELLOW+"Match starts in "+n+"...");b.sendMessage(ChatColor.YELLOW+"Match starts in "+n+"...");n--;}}.runTaskTimer(p,0L,20L);}
 public boolean isInMatch(UUID u){return matches.containsKey(u);}public void markCombat(Player a,Player b){p.cards().tagCombat(a,b);}
 public void onPlayerDeath(Player loser){Match m=matches.get(loser.getUniqueId());if(m==null)return;UUID winner=m.a.equals(loser.getUniqueId())?m.b:m.a;Player w=Bukkit.getPlayer(winner);if(w!=null){p.profiles().win(w);p.profiles().loss(loser);if(m.official){p.economy().addCoins(w,p.getConfig().getInt("settings.economy.official-win-cc",250));p.economy().missionEvent(w,"official_wins_1",1);p.economy().missionEvent(w,"official_wins_3",1);} }if(m.official){p.economy().missionEvent(loser,"official_matches_5",1);if(w!=null)p.economy().missionEvent(w,"official_matches_5",1);}end(m);}
 public void onPlayerQuit(Player x){Match m=matches.get(x.getUniqueId());if(m==null)return;UUID winner=m.a.equals(x.getUniqueId())?m.b:m.a;Player w=Bukkit.getPlayer(winner);if(w!=null){p.profiles().win(w);p.profiles().loss(x);if(m.official){p.economy().addCoins(w,p.getConfig().getInt("settings.economy.official-win-cc",250));p.economy().missionEvent(w,"official_wins_1",1);p.economy().missionEvent(w,"official_wins_3",1);}}end(m);}
 private void end(Match m){matches.remove(m.a);matches.remove(m.b);restore(m.a);restore(m.b);Player a=Bukkit.getPlayer(m.a),b=Bukkit.getPlayer(m.b);if(a!=null)p.cards().clearCombatTag(a);if(b!=null)p.cards().clearCombatTag(b);}
 private void restore(UUID u){Player p1=Bukkit.getPlayer(u);Location l=returns.remove(u);if(p1!=null&&l!=null)p1.teleport(l);}
 public Location readLocation(String which){String w=p.getConfig().getString("settings.arena.world","world");World world=Bukkit.getWorld(w);if(world==null)return null;String b="settings.arena."+which;return new Location(world,p.getConfig().getDouble(b+".x"),p.getConfig().getDouble(b+".y"),p.getConfig().getDouble(b+".z"), (float)p.getConfig().getDouble(b+".yaw"),(float)p.getConfig().getDouble(b+".pitch"));}
 public void shutdown(){for(Match m:new HashSet<Match>(matches.values()))end(m);pending.clear();}
 public static final class Match{final UUID a,b;final boolean official;Match(UUID a,UUID b,boolean o){this.a=a;this.b=b;this.official=o;}}
}
