package com.cardcombat;
import java.util.*;import org.bukkit.*;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.*;import org.bukkit.event.inventory.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;
public final class CombatListener implements Listener{
 private final CardCombatPlugin p;public CombatListener(CardCombatPlugin p){this.p=p;}
 @EventHandler(priority=EventPriority.HIGHEST)public void interact(PlayerInteractEvent e){Player x=e.getPlayer();if(!p.isBattleMode(x))return;ItemStack i=e.getItem();String id=p.cards().cardId(i);if(id==null)return;CardDefinition c=p.cards().get(id);if(c==null)return;if(e.getAction()!=Action.RIGHT_CLICK_AIR&&e.getAction()!=Action.RIGHT_CLICK_BLOCK)return;e.setCancelled(true);if(c.type.equals("DOMAIN_HOME")){p.cards().enterOrExitHome(x);return;}if(c.type.equals("DOMAIN_CLOUD")){p.cards().useCloud(x);return;}LivingEntity target=findTarget(x,c);p.cards().use(x,id,target);}
 private LivingEntity findTarget(Player p,CardDefinition c){if(c.type.startsWith("DOMAIN_")||c.type.equals("FORM")||c.type.equals("PLAYANOO_TECH")||c.type.startsWith("AREA_")||c.type.equals("SUMMON")||c.type.equals("HEAL")||c.type.equals("REGEN")||c.type.equals("SPEED")||c.type.equals("HASTE")||c.type.equals("RESIST")||c.type.equals("SHIELD")||c.type.equals("DASH"))return null;return rayTarget(p,c.range);}
 private LivingEntity rayTarget(Player p,double range){VectorRay r=new VectorRay(p.getEyeLocation(),range);for(Entity e:p.getNearbyEntities(range,range,range))if(e instanceof LivingEntity&&e!=p){LivingEntity l=(LivingEntity)e;if(r.hits(l))return l;}return null;}
 @EventHandler public void inventoryClick(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player))return;Player x=(Player)e.getWhoClicked();String title=e.getView().getTitle();if(title==null)return;if(title.startsWith(CardMenu.LIBRARY_PREFIX)){e.setCancelled(true);int slot=e.getRawSlot();if(slot<0)return;if(slot<12){String[] cls=p.classes();if(slot<cls.length&&!p.profiles().hasClass(x)){if(p.profiles().setClass(x,cls[slot])){x.sendMessage(ChatColor.GREEN+"Class chosen: "+cls[slot]);x.closeInventory();p.cards().refreshHotbar(x);}return;}return;}if(slot==35){x.closeInventory();String cls=p.profiles().getClass(x);if(cls!=null&&!cls.isEmpty()){for(String id:new String[]{cls.toLowerCase()+"_home",cls.toLowerCase()+"_cloud"}){ItemStack card=p.cards().createItem(id,1);if(card!=null)x.getInventory().addItem(card);}}return;}if(slot>=12&&slot<=34){ItemStack i=e.getCurrentItem();String id=p.cards().cardId(i);if(id==null)return;CardDefinition c=p.cards().get(id);if(c==null)return;boolean unlocked=p.isStaff(x)||p.economy().owns(x,id)||c.type.startsWith("DOMAIN_")||c.type.startsWith("PLAYANOO")||c.type.equals("FORM");if(!unlocked)return;for(int h=0;h<9;h++)if(x.getInventory().getItem(h)==null){x.getInventory().setItem(h,p.cards().createItem(id,1));x.sendMessage(ChatColor.GREEN+"Added "+ChatColor.stripColor(ChatColor.translateAlternateColorCodes('&',c.name))+" to hotbar.");return;}x.sendMessage(ChatColor.YELLOW+"Your hotbar is full.");}return;}if(title.startsWith(CardMenu.DOMAINS)){e.setCancelled(true);ItemStack i=e.getCurrentItem();String id=p.cards().cardId(i);if(id==null)return;for(int h=0;h<9;h++)if(x.getInventory().getItem(h)==null){x.getInventory().setItem(h,p.cards().createItem(id,1));x.closeInventory();return;}return;}if(title.startsWith(CardMenu.PROFILE)){e.setCancelled(true);int page=0;int marker=title.indexOf("[Cosmetics ");if(marker>=0){try{page=Integer.parseInt(title.substring(marker+11,title.indexOf('/',marker)))-1;}catch(Exception ignored){}}int slot=e.getRawSlot();if(slot==52&&page>0){x.openInventory(new CardMenu(p).createProfile(x,page-1));return;}if(slot==53&&title.contains("[Cosmetics ")&&!title.endsWith("/1]")){if(title.indexOf('/')>marker&&title.charAt(title.indexOf('/')+1)!='1'){x.openInventory(new CardMenu(p).createProfile(x,page+1));return;}}String key=CardMenu.profileKey(e.getCurrentItem());if(key!=null&&key.startsWith("TITLE:")){String t=key.substring(6);if(p.profiles().unlockedTitles(p.profiles().getWins(x)).contains(t)||p.isStaff(x))p.profiles().setTitle(x,t);}else if(key!=null&&key.startsWith("COSMETIC:")){String cc=key.substring(9);if(p.profiles().unlockedCosmetics(p.profiles().getWins(x)).contains(cc)||p.isStaff(x))p.profiles().setCosmetic(x,cc);}return;}if(title.startsWith(ChatColor.DARK_GRAY+"BattleCards")){e.setCancelled(true);}}
@EventHandler public void damage(EntityDamageByEntityEvent e){if(!(e.getDamager() instanceof Player))return;Player a=(Player)e.getDamager();if(!(e.getEntity() instanceof Player))return;Player b=(Player)e.getEntity();if(!p.isBattleMode(a)||!p.isBattleMode(b))return;p.cards().tagCombat(a,b);if(p.isMageArmorMode(b))e.setDamage(e.getDamage()*p.getConfig().getDouble("settings.mage-armor.damage-multiplier",0.65));}
 @EventHandler public void death(PlayerDeathEvent e){Player loser=e.getEntity();p.challenges().onPlayerDeath(loser);}
 @EventHandler public void quit(PlayerQuitEvent e){Player x=e.getPlayer();if(p.cards().isCombatTagged(x)){p.cards().markCombatLogged(x);p.challenges().onPlayerQuit(x);}p.matchmaking().remove(x.getUniqueId());p.practiceBots().removeAll(x);}
 @EventHandler public void join(PlayerJoinEvent e){Player x=e.getPlayer();if(p.cards().consumeCombatLogged(x))x.setHealth(0);}
 @EventHandler public void breakBlock(BlockBreakEvent e){Player x=e.getPlayer();if(p.cards().isHomeWorld(x.getWorld())&&!p.cards().canBuildInHome(x)){e.setCancelled(true);return;}if(p.isBattleMode(x)&&p.getConfig().getBoolean("settings.mode.prevent-block-break",true)&&!p.cards().canBuildInHome(x))e.setCancelled(true);}
 @EventHandler public void place(BlockPlaceEvent e){Player x=e.getPlayer();if(p.cards().isHomeWorld(x.getWorld())&&!p.cards().canBuildInHome(x)){e.setCancelled(true);return;}if(p.isBattleMode(x)&&p.getConfig().getBoolean("settings.mode.prevent-block-place",true)&&!p.cards().canBuildInHome(x))e.setCancelled(true);}
 @EventHandler public void drop(PlayerDropItemEvent e){if(p.isBattleMode(e.getPlayer()))e.setCancelled(true);}
 @EventHandler public void damageAny(EntityDamageEvent e){if(e.getEntity() instanceof Player&&p.cards().shielded((Player)e.getEntity()))e.setCancelled(true);}
 @EventHandler public void deathSummon(EntityDeathEvent e){if(p.cards().isSummon(e.getEntity()))p.cards().onSummonDeath(e.getEntity());}
 private static final class VectorRay{final Location o;final Vector d;final double range;VectorRay(Location o,double r){this.o=o;d=o.getDirection().normalize();range=r;}boolean hits(LivingEntity e){Vector v=e.getEyeLocation().toVector().subtract(o.toVector());double l=v.length();return l<=range&&d.dot(v.normalize())>=.88;}}
}
