package com.cardcombat;
import java.io.File;import java.util.*;import org.bukkit.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;
public final class EconomyManager{
 private final CardCombatPlugin p;private final File f;private final Map<UUID,Integer>coins=new HashMap<UUID,Integer>();private final Map<UUID,Set<String>>owned=new HashMap<UUID,Set<String>>();private final Map<UUID,Map<String,Integer>>mission=new HashMap<UUID,Map<String,Integer>>();private final Map<UUID,Long>reset=new HashMap<UUID,Long>();
 public EconomyManager(CardCombatPlugin p){this.p=p;f=new File(p.getDataFolder(),"economy.yml");load();}
 public void load(){coins.clear();owned.clear();mission.clear();reset.clear();if(!f.exists())return;YamlConfiguration y=YamlConfiguration.loadConfiguration(f);org.bukkit.configuration.ConfigurationSection s=y.getConfigurationSection("players");if(s==null)return;for(String k:s.getKeys(false))try{UUID u=UUID.fromString(k);coins.put(u,s.getInt(k+".cc"));Set<String>set=new LinkedHashSet<String>(s.getStringList(k+".owned"));owned.put(u,set);Map<String,Integer>m=new HashMap<String,Integer>();org.bukkit.configuration.ConfigurationSection ms=s.getConfigurationSection(k+".missions");if(ms!=null)for(String q:ms.getKeys(false))m.put(q,ms.getInt(q));mission.put(u,m);reset.put(u,s.getLong(k+".reset"));}catch(Exception ignored){}}
 public synchronized void save(){YamlConfiguration y=new YamlConfiguration();Set<UUID>ids=new HashSet<UUID>();ids.addAll(coins.keySet());ids.addAll(owned.keySet());ids.addAll(mission.keySet());for(UUID u:ids){String b="players."+u;y.set(b+".cc",getCoins(u));y.set(b+".owned",new ArrayList<String>(set(u)));Map<String,Integer>m=mission.get(u);if(m!=null)for(Map.Entry<String,Integer>e:m.entrySet())y.set(b+".missions."+e.getKey(),e.getValue());y.set(b+".reset",reset.get(u));}try{if(!p.getDataFolder().exists())p.getDataFolder().mkdirs();y.save(f);}catch(Exception e){p.getLogger().warning("Could not save economy.yml: "+e.getMessage());}}
 private Set<String>set(UUID u){Set<String>s=owned.get(u);if(s==null){s=new LinkedHashSet<String>();owned.put(u,s);}return s;}private void window(UUID u){long now=System.currentTimeMillis();Long r=reset.get(u);if(r==null||now-r>=86400000L){mission.put(u,new HashMap<String,Integer>());reset.put(u,now);}}
 public int getCoins(Player p){return getCoins(p.getUniqueId());}public int getCoins(UUID u){Integer n=coins.get(u);return n==null?0:n;}public void addCoins(Player p,int n){if(n<=0)return;coins.put(p.getUniqueId(),getCoins(p)+n);save();}public boolean takeCoins(Player p,int n){if(n<0||getCoins(p)<n)return false;coins.put(p.getUniqueId(),getCoins(p)-n);save();return true;}
 public boolean owns(Player p,String id){return p!=null&&(p.isOp()||p.hasPermission("battlecards.staff")||set(p.getUniqueId()).contains(id.toLowerCase()));}public void grant(Player p,String id){set(p.getUniqueId()).add(id.toLowerCase());save();}
 public int price(CardDefinition c){if(c==null||c.type.startsWith("DOMAIN_")||c.type.equals("PLAYANOO")||c.type.equals("FORM"))return -1;if(c.rarity.equalsIgnoreCase("Legendary"))return 800;if(c.rarity.equalsIgnoreCase("Epic"))return 550;if(c.rarity.equalsIgnoreCase("Rare"))return 325;if(c.rarity.equalsIgnoreCase("Uncommon"))return 175;return 100;}
 public void ensureStarterCards(Player p,String cls){int n=0;for(CardDefinition c:this.p.cards().all()){if(c.cardClass.equalsIgnoreCase(cls)&&!c.type.startsWith("DOMAIN_")&&!c.type.equals("PLAYANOO")&&n<9){grant(p,c.id);n++;}}}
 public boolean buy(Player p,CardDefinition c){if(c==null)return false;if(owns(p,c.id)){p.sendMessage(ChatColor.YELLOW+"You already own that card.");return false;}if(!c.cardClass.equalsIgnoreCase(this.p.profiles().getClass(p))){p.sendMessage(ChatColor.RED+"That card belongs to another class.");return false;}int price=price(c);if(price<0){p.sendMessage(ChatColor.RED+"That card is not sold in the shop.");return false;}if(this.p.isStaff(p)){grant(p,c.id);p.sendMessage(ChatColor.GREEN+"Admin bypass: "+c.name+" unlocked for 0 CC.");return true;}if(!takeCoins(p,price)){p.sendMessage(ChatColor.RED+"You need "+(price-getCoins(p))+" more CC.");return false;}grant(p,c.id);p.sendMessage(ChatColor.GREEN+"Bought "+c.name+" for "+price+" CC.");return true;}
 public void missionEvent(Player p,String key,int amount){window(p.getUniqueId());Map<String,Integer>m=mission.get(p.getUniqueId());int before=m.containsKey(key)?m.get(key):0;int goal=missionGoal(key);if(before>=goal)return;int after=Math.min(goal,before+Math.max(0,amount));m.put(key,after);if(after>=goal){int reward=missionReward(key);addCoins(p,reward);p.sendMessage(ChatColor.GOLD+"Mission complete: "+missionName(key)+" — +"+reward+" CC");}save();}
 public int missionProgress(Player p,String k){window(p.getUniqueId());Map<String,Integer>m=mission.get(p.getUniqueId());Integer n=m.get(k);return n==null?0:n;}public int missionGoal(String k){if(k.equals("official_wins_1"))return 1;if(k.equals("official_wins_3"))return 3;if(k.equals("official_matches_5"))return 5;return 1;}public int missionReward(String k){if(k.equals("official_wins_1"))return 150;if(k.equals("official_wins_3"))return 500;if(k.equals("official_matches_5"))return 900;return 100;}public String missionName(String k){if(k.equals("official_wins_1"))return "Win 1 official match";if(k.equals("official_wins_3"))return "Win 3 official matches";if(k.equals("official_matches_5"))return "Complete 5 official matches";return k;}
 public List<String> missionKeys(){return Arrays.asList("official_wins_1","official_wins_3","official_matches_5");}
 public void showMissions(Player p){p.sendMessage(ChatColor.GOLD+"=== Card Coin Missions ===");for(String k:missionKeys())p.sendMessage(ChatColor.YELLOW+missionName(k)+ChatColor.GRAY+" — "+missionProgress(p,k)+"/"+missionGoal(k)+ChatColor.GREEN+" — "+missionReward(k)+" CC");}
}
