package com.cardcombat;
import java.util.*;import org.bukkit.*;import org.bukkit.entity.*;import org.bukkit.metadata.FixedMetadataValue;import org.bukkit.potion.*;
public final class PracticeBotManager{private final CardCombatPlugin p;private final CardManager cards;private final Map<UUID,BotState>bots=new HashMap<UUID,BotState>();private final Random random=new Random();private static final String META="battlecards_practice_bot";public PracticeBotManager(CardCombatPlugin p,CardManager c){this.p=p;cards=c;}
 public Zombie spawn(Player owner,String difficulty,String cls){removeAll(owner);Location l=owner.getLocation().clone().add(owner.getLocation().getDirection().multiply(6));Zombie z=(Zombie)owner.getWorld().spawnEntity(l,EntityType.ZOMBIE);z.setCustomName(ChatColor.translateAlternateColorCodes('&',"&bPractice Bot &7["+cls+" / "+difficulty+"]"));z.setCustomNameVisible(true);z.setMetadata(META,new FixedMetadataValue(p,owner.getUniqueId().toString()));z.setMaxHealth(60);z.setHealth(60);bots.put(z.getUniqueId(),new BotState(z.getUniqueId(),owner.getUniqueId(),difficulty,cls,System.currentTimeMillis()));owner.sendMessage(ChatColor.GREEN+"Spawned a "+difficulty+" "+cls+" practice bot.");return z;}
 public boolean isBot(Entity e){return e!=null&&e.hasMetadata(META);}public void remove(UUID id){BotState s=bots.remove(id);if(s!=null){Entity e=Bukkit.getEntity(id);if(e!=null)e.remove();}}public void removeAll(Player owner){for(BotState s:new ArrayList<BotState>(bots.values()))if(s.owner.equals(owner.getUniqueId()))remove(s.bot);}
 public void tick(){long now=System.currentTimeMillis();for(BotState s:new ArrayList<BotState>(bots.values())){Entity be=Bukkit.getEntity(s.bot);Player owner=Bukkit.getPlayer(s.owner);if(!(be instanceof Zombie)||owner==null){remove(s.bot);continue;}Zombie z=(Zombie)be;if(!z.getWorld().equals(owner.getWorld())){z.teleport(owner.getLocation().add(0,0,5));continue;}double range=z.getLocation().distance(owner.getLocation());if(range>30){z.teleport(owner.getLocation().add(owner.getLocation().getDirection().multiply(5)));continue;}z.setTarget(owner);long delay=s.delay();if(now-s.last<delay)continue;s.last=now;CardDefinition c=randomCard(s.cls);if(c==null)continue;botCast(z,owner,c);}}
 private CardDefinition randomCard(String cls){List<CardDefinition>l=new ArrayList<CardDefinition>();for(CardDefinition c:cards.all())if(c.cardClass.equalsIgnoreCase(cls)&&!c.type.startsWith("DOMAIN_")&&!c.type.equals("FORM")&&!c.type.startsWith("PLAYANOO"))l.add(c);return l.isEmpty()?null:l.get(random.nextInt(l.size()));}
 private void botCast(Zombie z,Player target,CardDefinition c){double d=z.getLocation().distance(target.getLocation());if(d>c.range&&c.range>0){z.setVelocity(target.getLocation().toVector().subtract(z.getLocation().toVector()).normalize().multiply(.5));return;}double dmg=Math.max(1,c.power*.45);target.damage(dmg,z);z.getWorld().spawnParticle(particle(c.element),target.getLocation().add(0,1,0),30,.6,.7,.6,.04);if(c.type.equals("IGNITE")||c.type.equals("AREA_IGNITE"))target.setFireTicks(c.duration*20);if(c.type.equals("POISON"))target.addPotionEffect(new PotionEffect(PotionEffectType.POISON,c.duration*20,0));if(c.type.equals("SLOW")||c.type.equals("AREA_SLOW"))target.addPotionEffect(new PotionEffect(PotionEffectType.SLOW,c.duration*20,0));if(c.type.equals("WITHER"))target.addPotionEffect(new PotionEffect(PotionEffectType.WITHER,c.duration*20,0));if(c.type.equals("WEAKNESS"))target.addPotionEffect(new PotionEffect(PotionEffectType.WEAKNESS,c.duration*20,0));if(c.type.contains("KNOCKBACK"))target.setVelocity(target.getLocation().toVector().subtract(z.getLocation().toVector()).normalize().multiply(1.0).setY(.4));}
 private Particle particle(String e){if(e==null)return Particle.CRIT;String x=e.toLowerCase();if(x.contains("fire")||x.contains("dragon"))return Particle.FLAME;if(x.contains("water")||x.contains("ice"))return Particle.SNOWBALL;if(x.contains("wind"))return Particle.CLOUD;if(x.contains("light"))return Particle.END_ROD;if(x.contains("shadow")||x.contains("soul"))return Particle.SPELL_WITCH;if(x.contains("mech")||x.contains("emp"))return Particle.REDSTONE;return Particle.CRIT;}
 public void shutdown(){for(BotState s:new ArrayList<BotState>(bots.values()))remove(s.bot);bots.clear();}private static final class BotState{final UUID bot,owner;final String difficulty,cls;long last;BotState(UUID b,UUID o,String d,String c,long l){bot=b;owner=o;difficulty=d;cls=c;last=l;}long delay(){if(difficulty.equalsIgnoreCase("hard"))return 900;if(difficulty.equalsIgnoreCase("easy"))return 3000;return 1700;}}
}
